### ISSUE TITLE
[Bug] Back button is not working in notification setting

### ISSUE THREAD

**Issue by uderbashi** [jameskokoska/Cashew#791]
**Describe the bug**
Android's back button (the one at the bottom of the screen) does not work in the notification settings. 

**How to reproduce**
Settings -> Notifications -> (press android's back button)
Note that the UI's button (the one in the upper left corner) works.

**Details**
 - Device: Samsung S20FE
 - App Version: 6.0.9+451

**Additional notes**
Maybe worth noting that I have notifications disabled. Don't know if that plays any role here.

**Comment by jameskokoska** [comment]
This has been fixed in the latest beta. It is related to issues with #756.
If this is still an active issue, add an update and this ticket can be further discussed and reopened as necessary. See #725 for Beta Testing instructions and information.

**Comment by uderbashi** [comment]
> This has been fixed in the latest beta. It is related to issues with [#756](https://github.com/jameskokoska/Cashew/issues/756). If this is still an active issue, add an update and this ticket can be further discussed and reopened as necessary. See [#725](https://github.com/jameskokoska/Cashew/issues/725) for Beta Testing instructions and information.

Hey James,

I've tried this, and it seemed that it was resolved until I tried disabling the notifications and the issue seems to persist.

The way to reproduce:
Go to Android settings and disable the notifications permission for Cashew - > Cashew in-app Settings -> Notifications -> (press android's back button)

This only is an issue if the banner "Notifications Disabled" is there. 

Funnily enough, when pressing the back button in very rapid succession (~4-5 times a second) it works. Which makes me think that the banner maybe "gets dismissed" and then enables the back button, and that would suggest that there is probably some active loop that is checking notifications permissions constantly. And when the loop runs it triggers something that blocks Androids back button? 

But that's a theory.

**Comment by jameskokoska** [comment]
Thanks for the update! I wasn't able to replicate the behaviour - even with notifications disabled the back button still works for me. There also isn't any code preventing the route from popping with the back button on this page, so I'm not sure what's causing this.

**Comment by uderbashi** [comment]
https://github.com/user-attachments/assets/70362a10-7597-48ed-8864-314a7573f8be

I have just reinstalled the app, and the issue is still there. Above is the screen recording.

On a side note, I can say that backup and restore seems to work impeccably, and I love that it also backs up the settings with it so that I did not have to rework the UI.
